// Representative validation seed, not a verified household directory.
// Meena, Kavin and Diya are example names; replace them with consented aliases.
// Keep real aliases in the bakeoff form or ignored local JSON, not Git.
export const KEYTERMS: string[] = [
  "Nilumi",
  "Nishanth",
  "Meena",
  "Kavin",
  "Diya",
  "Amma",
  "Appa",
  "Paati",
  "Thatha",
  "Amul",
  "Aavin",
  "Tata",
  "Bisleri",
  "BigBasket",
  "Zomato",
  "Swiggy",
  "Flipkart",
  "Myntra",
  "Samsung",
  "iPhone",
  "Jio",
  "Airtel",
  "PhonePe",
  "Google Pay",
  "Dolo",
  "Dettol",
  "Harpic",
  "Surf Excel",
  "Aashirvaad",
  "Britannia",
  "T Nagar",
  "Anna Nagar",
  "Velachery",
  "Tambaram",
  "OMR",
  "ECR",
  "Mylapore",
  "Adyar",
  "Chennai",
  "Coimbatore",
  "milk",
  "curd",
  "rice",
  "dal",
  "doctor",
  "school",
  "birthday",
  "anniversary",
  "பால்",
  "சாதம்",
];
