#!/usr/bin/env node
// Extracts the Phosphor icons the specimen uses (regular / fill / duotone) into specimen/icons.js.
// Run: node specimen/build-icons.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
// @phosphor-icons/core doesn't export package.json, so resolve the linked folder directly.
const core = join(here, "..", "node_modules", "@phosphor-icons", "core");

const NAMES = [
  "sun", "list-checks", "chat-circle-dots", "calendar-check", "book-bookmark", "bell", "microphone", "house",
  "users", "lock", "link-simple", "lightbulb", "check", "check-circle", "x", "arrow-counter-clockwise",
  "pencil-simple", "trash", "caret-left", "caret-right", "shopping-cart", "shield-check", "graduation-cap",
  "drop", "gift", "warning", "info", "wifi-slash", "magnifying-glass", "plus", "heartbeat", "clock",
  "gear-six", "user-circle", "dots-three", "tray", "moon", "text-aa", "waveform", "receipt", "car",
  "washing-machine", "basket", "sparkle", "arrows-clockwise", "chart-bar", "code", "funnel", "download-simple",
];
const WEIGHTS = ["regular", "bold", "fill", "duotone"];

const icons = {};
for (const name of NAMES) {
  icons[name] = {};
  for (const w of WEIGHTS) {
    const file = join(core, "assets", w, w === "regular" ? `${name}.svg` : `${name}-${w}.svg`);
    const svg = readFileSync(file, "utf8");
    icons[name][w] = svg.replace(/^<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "");
  }
}
writeFileSync(
  join(here, "icons.js"),
  `// Generated by build-icons.mjs from @phosphor-icons/core (MIT). Do not edit.\nwindow.PHOSPHOR = ${JSON.stringify(icons)};\n`,
);
console.log(`Wrote ${NAMES.length} icons × ${WEIGHTS.length} weights to specimen/icons.js`);
